---
title: "Title_of_Website"
author: "CForster"
date: "May 21, 2018"
output: html_document
toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Loading the libraries 
```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
library(DT)
library(leaflet)
```

# Read in the data 
```{r}
esc <- read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/knb.92020.1", method = "libcurl"), 
                stringsAsFactors = FALSE)
```

# Filter and process the data 
```{r}
median_esc <- esc %>% 
  separate(sampleDate, c("Year", "Month", "Day"), sep = "-") %>% 
  group_by(Species, SASAP.Region, Year, Location) %>% 
  summarize(escapement = sum(DailyCount, na.rm = T)) %>% #na.rm=T is a trick to deal with NAs  
  group_by(Species) %>% 
  summarize(median_escapement = median(escapement))
```

# Make a plot
```{r}
ggplot(median_esc, aes(Species, median_escapement)) +
  geom_col() +
  coord_flip()
```

# Locations for the map 

```{r}
locations <- esc %>% 
  distinct(Location, Latitude, Longitude) %>% #distict is a useful function
  drop_na()

datatable(locations)
```

# Leaflet Map 

```{r}
leaflet(locations) %>% #I want a map 
  addTiles() %>% 
  addMarkers(~ Longitude, ~ Latitude, popup = ~ Location) #leaflet like ~ in front of the columns

locs <- locations %>% mutate(Longitude = abs(Longitude) * -1)

markerIcon <- makeIcon(
  iconUrl = "https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.3.1/images/marker-icon.png",
  iconWidth = 25, iconHeight = 41,
  iconAnchorX = 12, iconAnchorY = 41,
  shadowUrl = "https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.3.1/images/marker-shadow.png",
  shadowWidth = 41, shadowHeight = 41,
  shadowAnchorX = 13, shadowAnchorY = 41
)

leaflet(locs) %>% 
  addTiles() %>% 
  addMarkers(~ Longitude, ~ Latitude, popup = ~ Location, icon = markerIcon)
```

